load("//cc:defs.bzl", "cc_library")

cc_library(
    name = "world",
    srcs = [
        "world.cpp",
    ],
    hdrs = [
        "world.h",
    ],
    includes = ["."],
    visibility = ["//visibility:public"],
)